### 1. Create a 2d numpy array with 25 elements


In [2]:
import numpy as np

In [3]:
a = np.arange(25).reshape(5,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Extra: 
Extract array( [1, 7, 13, 19] )

In [14]:
a[[0,1,2,3], [1,2,3,4]]

array([ 1,  7, 13, 19])

### 2. Extract all the numbers divisible by 3 using masking

In [18]:
divisibleByThree = (a % 3 == 0)

In [21]:
a[divisibleByThree].reshape(3,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])