In [5]:
import numpy as np

In [50]:
x = np.array([1,2,3,4,5])
y = np.array([[6],[7],[8],[9]])

In [51]:
print(x.shape)
print(y.shape)

(5,)
(4, 1)


np.newaxis can be used to increase the dimension of a give array by one or more dimension i.e.
1. 1D array will change to 2D
2. 2D array will change to 3D
3. nD array will change to (n+1)D

# Lets Covert array 'x' into a column vector
We simply need to add a new axis along the second dimension



In [58]:
print(x)
print(x.shape)
col2d = x[:, np.newaxis]
print(col2d.shape)
col2d

[1 2 3 4 5]
(5,)
(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [54]:
row3d = y[:, np.newaxis]

In [55]:
row3d

array([[[6]],

       [[7]],

       [[8]],

       [[9]]])

In [56]:
row3d.shape

(4, 1, 1)

In [61]:
y = np.array([1,2,3,4,5])

In [64]:
y[:, np.newaxis].shape

(5, 1)

In [63]:
y.shape

(5,)

In [83]:
x = np.array([[1,2,3,4],[4,5,6,3]])
y = np.arange(24).reshape(2,3,4)

In [88]:
print(x)
print(x.shape)
print(y.shape)

x = x[:, np.newaxis, :]
x+y

[[[1 2 3 4]]

 [[4 5 6 3]]]
(2, 1, 4)
(2, 3, 4)


array([[[[ 1,  3,  5,  7],
         [ 5,  7,  9, 11],
         [ 9, 11, 13, 15]],

        [[13, 15, 17, 19],
         [17, 19, 21, 23],
         [21, 23, 25, 27]]],


       [[[ 4,  6,  8,  6],
         [ 8, 10, 12, 10],
         [12, 14, 16, 14]],

        [[16, 18, 20, 18],
         [20, 22, 24, 22],
         [24, 26, 28, 26]]]])

In [78]:
x = x[:, np.newaxis, :]

In [79]:
x.shape


(2, 1, 3)

In [80]:
x

array([[[1, 2, 3]],

       [[4, 5, 6]]])