In [2]:
import numpy as np


In [3]:
arr = np.array([-1,2,3,-4,5], dtype='float32')

In [4]:
arr//0


/home/paritosh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan], dtype=float32)

In [23]:
np.zeros((2,2), dtype='float32')

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [24]:
np.ones((3,2), dtype='int64')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [25]:
a = np.arange(12).reshape(4,3)

In [26]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a[2,1]

7

In [28]:
a[1:,:]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
b = np.arange(24).reshape(2,3,4)

In [30]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
b[0,2,3]

11

In [32]:
b[:,1:,1:]

array([[[ 5,  6,  7],
        [ 9, 10, 11]],

       [[17, 18, 19],
        [21, 22, 23]]])

In [33]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
b[[0,1],[1,1],[1,2]]

array([ 5, 18])

In [36]:
b > 12

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [37]:
b[b>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [38]:
b.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [39]:
d = np.array([1,2,3,4,5])

In [40]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False